### ISSUE TITLE
How to handle translations

### ISSUE THREAD

**Issue by darccio** [HumanOps/HumanOps#5]
I would love to translate the texts to Spanish. How do you want to handle translations?

**Comment by andrepoleza** [comment]
Me too! I would like to translate to pt-BR. How can we do that?

**Comment by dywanik** [comment]
:+1: 
I could do Polish. Waiting for your reply. :)

**Comment by rsallar** [comment]
I could do Catalan. Ready to help!

**Comment by darccio** [comment]
Any news?

**Comment by nicolaevladescu** [comment]
Hello, i could do Romanian, also waiting in line feedback about how we could implement this.

**Comment by davidmytton** [comment]
Thanks for everyone's enthusiasm! The site currently isn't set up for translation support but this is something we'll certainly consider. We're putting together a roadmap for where we want to take HumanOps next so will keep this open for now.

**Comment by caiobegotti** [comment]
Any status about that @dmytton?
